name: workflow with dropdown

on: 
  workflow_dispatch:
    inputs:
      glue_streaming_job:
        description: 'Select the streaming Job name'
        required: true
        type: choice
        options:
          - mdsc-orders-completed
          - mdsc-orders-refunded
          - mdsc-delivery-reporting
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        default: None
        options:
          - None
          - development
          - staging
          - production
      job_action:
        description: 'Select the Start and Stop'
        required: true
        type: choice
        default: None
        options:
          - None
          - Start
          - Stop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Selected Environment
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"

      - name: Start the Glue streaming Job
        if: ${{ github.event.inputs.job_action == 'Start' }}
        run: echo "Start Job: ${{ github.event.inputs.glue_streaming_job }}"

      - name: Stop the Glue streaming Job
        if: ${{ github.event.inputs.job_action == 'Stop' }}
        run: echo "Stop Job: ${{ github.event.inputs.glue_streaming_job }}"
