name: workflow with dropdown

on: 
  workflow_dispatch:
    inputs:
    glue-streaming-job:
        description: 'Select the streaming Job name'
        required: true
        type: choice
        options:
          - mdsc-orders-completed
          - mdsc-orders-refunded
          - mdsc-delivery-reporting
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        default: None
        options:
          - None
          - development
          - staging
          - production
      job-action:
        description: 'Select the Start and Stop'
        required: true
        type: choice
        default: None
        options:
          - None
          - Start
          - Stop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Selected Environment
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"


      - name: Start the Glue streaming Job
        if: ${{ github.event.inouts.job-action == 'Start' }}
        run: echo "Start Job"

      - name: Start the Glue streaming Job
        if: ${{ github.event.inouts.job-action == 'Stop' }}
        run: echo "Stop Job"
